### ISSUE TITLE
Error on Network Quality test

### ISSUE THREAD

**Issue by Koreysherwin** [DaveL17/Multitool#5]
Apr 7, 2024 at 10:59:21 AM
   Stopping plugin Multitool (pid 53682)
   Stopped plugin Multitool
   Upgrading plugin Multitool to newer version 2023.2.1 (previous version moved to trash)
   Loading plugin "Multitool 2023.2.1" using API v3.2
   Starting plugin "Multitool 2023.2.1" (pid 55253)
   Started plugin "Multitool 2023.2.1"

Apr 7, 2024 at 10:59:52 AM
   Multitool Error                 Error in plugin execution UiValidate:

  File "plugin.py", line 682, in network_quality
  File "plugin.py", line 647, in network_quality_test_os
type: could not convert string to float: '13.6.6'

Indigo version: 2023.2.0 
MACOS : 13.6.6

**Comment by DaveL17** [comment]
Thanks - can reproduce here as well. Not sure what changed, but I'm on the case.

**Comment by DaveL17** [comment]
This bug is fixed in release [2023.2.2](https://github.com/DaveL17/Multitool/releases/tag/2023.2.2).
